### ISSUE TITLE
pcf clears bound fields for existing record

### ISSUE THREAD

**Issue by malkhawaja** [garethcheyne/PCF-FluentUi-AutoComplete-Boilerplate#2]
Hi,
thanks for your pcf and the great idea behind it.
I tried to modify it up to my requirements to use it for the same API (NZBN), and I added 4 more fields (Output parameters) and the pcf is working just fine on a new form, but the problem is for an existing record (e.g. in Account table) when I open the account record, it clears all the values in the bound fields (except the `value` bound field).
i am not sure what should I do the prevent the pcf from clearing the values onload of the existing record.
appreciate you kind help.
_Note: I am not a pro coder, but willing to learn new things related to power platform_

**Comment by garethcheyne** [comment]
Yeah, I did notice that myself and I have changed my production version.  I am just working at the very min of some updated and tiding my code around useEffect.  This was my first React project also.   

Look at the browser console, and you will see why it clears the value, and you could fix that yourself if you dont want to wait for my pending update.  I have a few other project on at work so cant promises it will happen straight away.

**Comment by malkhawaja** [comment]
is there a way you can suggest me to do for the useEffect?

**Comment by garethcheyne** [comment]
Just submitted an update, give that a crack, this is the same logic I have currently in my production env, only difference is that I'm addressing about 15 fields, in Dynamics. I am happy to share my Production version for NZBN, but I have a full solution with custom fields in it. ping me on LinkedIn and I can give you a link.

**Comment by malkhawaja** [comment]
actually I fixed the clearing issue... but created another issue with the onclear button... it does not work any more, but wouldn't mind take a look at your production solution.
Thanks
