### ISSUE TITLE
Apply this control to Canvas App

### ISSUE THREAD

**Issue by randolphnz** [garethcheyne/PCF-FluentUi-AutoComplete-Boilerplate#3]
Hi,

I am wondering if this PCF control can be applied to Canvas app. I've tried to bind it to a field but it's complaining error loading the control. Any idea will be appreciated. 

Regards,
Randy

**Comment by garethcheyne** [comment]
Hey Randy,

I have tested my in-production iteration of this project and works perfectly fine.  Have you customised this in any way?

Flick me a msg on LinkedIn.

![Screenshot 2023-10-30 084952](https://github.com/garethcheyne/PCF-FluentUi-AutoComplete-Boilerplate/assets/12602172/9c3ee780-392a-4ccf-887f-c0cb8108d6c8)
![Screenshot 2023-10-30 084931](https://github.com/garethcheyne/PCF-FluentUi-AutoComplete-Boilerplate/assets/12602172/0d71f7f6-c00b-4aff-b110-6e1efa122461)

**Comment by randolphnz** [comment]
Hi Gareth,

Really appreciated your quick response.

I assume it might be related to my configuration. Do I need to create an
Edit Form and bind this PCF control to the form field?

Regards,
Randy
